"""
FILE: logic/vidhi/kniti_nisedha.py
PAS-v2.0: 5.2 (Siddha) | PILLAR: Niṣedha (Prohibition)
TIMESTAMP: 2026-01-30 18:20:00
"""

class KnitiNisedha:
    """
    [VṚTTI]: क्ङिति च (१.१.५) - अङ्गाधिकारोक्तयोः गुणवृद्ध्योः निषेधः।
    The Gatekeeper: Prohibits Guṇa and Vṛddhi transformations when
    the following suffix is marked with K, G, or Ṅ.
    """

    @staticmethod
    def is_blocked(pratyaya_varnas, context=None) -> bool:
        """
        [VICCHEDA]: क् + ङ् + इति = क्ङिति (Locative plural/dual)
        Checks the inherited metadata tags of the suffix to decide
        if the preceding Guṇa/Vṛddhi operation must be killed.

        Args:
            pratyaya_varnas (list): The suffix varnas.
            context (dict, optional): Clinical context (unused here but required for API consistency).
        """
        if not pratyaya_varnas:
            return False

        # Standard PAS-v2.0 Tags generated by ItEngine:
        # 'kit'  from क् (1.3.8)
        # 'ngit' from ङ् (1.3.3)
        # 'gnit' from ग् (1.3.8)

        # We primarily check the first letter of the suffix which
        # acts as the carrier of the inherited "ghost tags".
        tags = getattr(pratyaya_varnas[0], 'sanjnas', set())

        target_tags = {"kit", "ngit", "gnit"}

        if any(tag in tags for tag in target_tags):
            return True

        return False

    @staticmethod
    def apply_1_1_5_block(anga, rule_id: str):
        """
        Siddha Audit: Logs the prohibition in the DNA trace of the Ik-varnas.
        Ensures the engine explains 'why' it didn't perform an operation.
        """
        ik_varnas = {'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ॠ', 'ऌ'}
        blocked_any = False

        for v in anga:
            if v.char in ik_varnas:
                v.trace.append(f"1.1.5 Block: Prohibited {rule_id} (Kṅiti Ca)")
                blocked_any = True

        return blocked_any