# core/pratyahara_engine.py
import json
from core.phonology import ad


class PratyaharaEngine:
    """
    प्रत्याहार-निर्माता (1.1.71)
    Standardized with 'ad' for absolute phonetic matching across all zones.
    """

    def __init__(self, json_path="data/shiva_sutras.json"):
        # Load and sanitize the 14 Shiva Sutras
        self.sutras = self._load_sutras(json_path)

    def _load_sutras(self, path):
        """Loads JSON and sanitizes varnas using the 'ad' physiological logic."""
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)["shiva_sutras"]
            # Pre-processing: Ensures database varnas match 'ad' output objects
            for sutra in data:
                # We extract the .char from the Varna objects generated by ad
                sutra['varnas'] = [v.char for v in ad("".join(sutra['varnas']))]
            return data

    def get_varnas(self, name: str) -> list:
        """
        Surgically decodes a Pratyahara name (e.g., 'अच्', 'हल्', 'इक्').
        Rule: आदिरन्त्येन सहेता (१.१.७१)
        """
        # Step 1: Parse the name using the 'ad' basis
        parsed = ad(name)
        if len(parsed) < 2:
            return []

        # Start character (e.g., 'अ') and End Marker (e.g., 'च्')
        adi = parsed[0].char
        antya_it = parsed[-1].char

        # Ensure parity with JSON it_varna (marker must be halant)
        if not antya_it.endswith('्'):
            antya_it += '्'

        pratyahara_list = []
        found_adi = False

        for sutra in self.sutras:
            current_varnas = sutra["varnas"]
            current_it = sutra["it_varna"]

            # आदि अन्वेषण: Find the starting point
            if adi in current_varnas or found_adi:
                start_idx = current_varnas.index(adi) if adi in current_varnas and not found_adi else 0
                found_adi = True

                # संकलन: Add characters while skipping the 'It' marker of each sutra
                for v in current_varnas[start_idx:]:
                    pratyahara_list.append(v)

                # सीमा अन्वेषण: Stop if this sutra's 'It' matches our target marker
                if current_it == antya_it:
                    return pratyahara_list

        return pratyahara_list if found_adi else []

    def is_in(self, char: str, pratyahara_name: str) -> bool:
        """
        Clinical check: Does 'char' belong to the range of 'pratyahara_name'?
        Includes Savarna expansion (1.1.69).
        """
        base_range = self.get_varnas(pratyahara_name)

        # सवर्ण-विस्तार (Savarna Mapping): 1.1.69 logic
        savarna_map = {
            'आ': 'अ', 'ई': 'इ', 'ऊ': 'उ', 'ॠ': 'ऋ'
        }

        check_char = savarna_map.get(char, char)
        return check_char in base_range